### ISSUE TITLE
Recovery file size

### ISSUE THREAD

**Issue by SirJohnDoe** [animetosho/ParPar#15]
In par2cmdline I used to have the option '-l' activated, to limit file size. I recall that this limits the recovery files to about the size of the .rars and splits them in multiple files if the total recovery size is greater. 

I realised after parpar was finished (using '-s8192000b' -r10%') that I only got a single recovery file, which is pretty much useless for posting to usenet. Then I found the '-p' switch, but for bigger archives this results in way too many files (e.g. my slize size is 8192000b, and if I limit it to 10 slices per file, then my recovery files are only 82 MB, which is good for smaller archives of about 3 to 5 GB, but for 50 GB archives I'd like them to be like 250 MB just like the rar size)

Is it possible to add a similar option as the '-l' switch in par2cmdline? Or did I miss something?

**Comment by animetosho** [comment]
Well, 250MB divided by 8000KB = 32, so `-p32` would give you ~250MB files.

But I've just added the ability to do the same thing as par2cmdline's `-l` option. It's available via the `-p1l` switch. Thanks for the suggestion!
