### ISSUE TITLE
Only one big par2 file gets created

### ISSUE THREAD

**Issue by JoshBeer** [animetosho/ParPar#18]
I installed parpar today and I'm so far loving it (what a difference in speed compared to par2cmdline).

I run it with the following settings:
`parpar -s2800000B -r5% -o xyz.par2 xyz*.rar`
The 2800000B are a multiple of my 700K nyuu article size and I always like to have 5% redundancy.

My problem is that it creates the "little" .par2 file and only ONE big .volxxx+xxx.par2 file.
In my current example it created an 3700MB file for about 74GB of archives.
How can I achieve the "normal" par2 behaviour of several .volxxx+xxx.par2 files?

PS: Sorry I know this isn't an issue but an user error from my side but I didn't know where else to ask this question.

**Comment by animetosho** [comment]
Try adding `-d pow2` to your command.

Thanks for the question by the way - it lets me know what confuses users and what can be done about it. ParPar was somewhat of a clean slate implementation, without much consideration for par2cmdline, so the current default seemed to make sense. However, as many are probably used to par2cmdline behaviour, it's probably a good idea to set defaults accordingly.

**Comment by JoshBeer** [comment]
Thank you, that seems to produce the behaviour I want. :)
