### ISSUE TITLE
Is --progress stdout working?

### ISSUE THREAD

**Issue by mbruel** [animetosho/ParPar#22]
Hi, 
It seems to not work on my env... Am I doing something wrong?

```
~/Downloads/testNgPost$ ~/apps/ParPar/bin/parpar.js --version
0.3.1
~/Downloads/testNgPost$ ~/apps/ParPar/bin/parpar.js -s1M -r8% -m1024M --progress stdout -o test.par2 jdk-8u171-linux-x64.tar.gz > out.txt 2> err.txt
~/Downloads/testNgPost$ wc -l out.txt err.txt 
  0 out.txt
  4 err.txt
  4 total
```
In fact --progress none is also doing the same :\

**Comment by animetosho** [comment]
What's the contents of err.txt?

**Comment by mbruel** [comment]
```
~/Downloads/testNgPost$ cat err.txt 
Multiply method used: Shuffle (256 bit), 8 threads
Generating 15 MiB recovery data (15 slices) from 182.05 MiB of data

PAR2 created. Time taken: 0.743 second(s)
```
There is no progress information, probably cause the file is too small and thus the generation too fast.
Anyway I would expect to have all this text on stdout also. This is not errors. Could you do it?

**Comment by animetosho** [comment]
There should always be progress output, as the 100% text is always written. `wc -l` counts *newlines* as opposed to lines, and the progress output never writes a newline, so perhaps you're thinking that there's no output on stdout. Try actually checking the size of out.txt itself, and if you open it, you may find the progress information there.

**Comment by mbruel** [comment]
my out.txt, not sure why...
But it seems to work well if I use it with ngPost.
Except I've still those 3 lines in stderr that are flagged as errors and thus displayed  [in red in ngPost GUI](https://i.ibb.co/KzKh6fV/Screenshot-2020-01-24-14-29-57.png)
Could write all that in stdout too plz?

**Comment by animetosho** [comment]
> my out.txt is empty, not sure why...

How are you checking that? Does `du -b out.txt` say the size is 0 bytes?

> Except I've still those 3 lines in stderr that are flagged as errors 

Use the `-q` flag.

**Comment by mbruel** [comment]
```
~/Downloads/testNgPost$ du -b out.txt 
2184	out.txt
```
but if I edit the file I don't see anything.... Is it cause you're using \r to rewrite on the same line ?

> Use the -q flag.

Cool that's perfect! (using --progress stdout -q)
 I thought the -q would force --progress none and thus I wouldn't get any progress indication.
That's what I understood from your description
```
       --progress            Progress indicator display, which can be either:
                                 none: disable progress output
                                 stderr: output a progress indicator to stderr
                                 stdout: output a progress indicator to stdout
                             Default is `stderr`, or `none` if `--quiet` is
                             specified.
  -q,  --quiet               Suppress information output. Errors will still be
                             displayed

```

**Comment by animetosho** [comment]
> but if I edit the file I don't see anything.... Is it cause you're using \r to rewrite on the same line ?

It uses magic terminal sequences to clear the line. Terminal editors may have a bit of an issue dealing with them, though most good text editors shouldn't have any problems.

> I thought the -q would force --progress none and thus I wouldn't get any progress indication.
That's what I understood from your description

If you have a wording suggestion, I can consider it.

**Comment by mbruel** [comment]
> Terminal editors may have a bit of an issue dealing with them, though most good text editors shouldn't have any problems.

true, vim is seeing the content
`Calculating:   2.61%[0GCalculating:   4.52%[0GCalculating:   5.47%[0GCalculating:   6.54%[0GCalculating:   8.20%[0GCalculating:   9.39%[0GCalculating:  10.35%[0GCalculating:  11.48%[0GCalculating:  12.31%[0GCalculating:  13.56%[0GCalculating:  14.69%[0GCalculating:  15.94%[0GCalculating:  17.13%[0GCalculating:  18.20%[0GCalculating:  19.15%[0GCalculating:  20.46%[0GCalculating:  21.65%[0GCalculating:  22.90%[0GCalculating:  23.91%[0GCalculating:  25.10%[0GCalculating:  26.29%[0GCalculating:  27.30%[0GCalculating:  28.55%[0GCalculating:  29.74%[0GCalculating:  30.51%[0GCalculating:  31.64%[0GCalculating:  32.83%[0GCalculating:  34.14%[0GCalculating:  35.21%[0GCalculating:  36.34%[0GCalculating:  37.59%[0GCalculating:  38.78%[0GCalculating:  39.97%[0GCalculating:  41.16%[0GCalculating:  41.93%[0GCalculating:  43.06%[0GCalculating:  44.25%[0GCalculating:  45.44%[0GCalculating:  46.40%[0GCalculating:  47.59%[0GCalculating:  48.72%[0GCalculating:  49.97%[0GCalculating:  51.27%[0GCalculating:  52.46%[0GCalculating:  53.36%[0GCalculating:  54.37%[0GCalculating:  55.56%[0GCalculating:  56.63%[0GCalculating:  57.58%[0GCalculating:  58.71%[0GCalculating:  59.96%[0GCalculating:  60.97%[0GCalculating:  61.86%[0GCalculating:  63.17%[0GCalculating:  64.24%[0GCalculating:  65.19%[0GCalculating:  66.38%[0GCalculating:  67.69%[0GCalculating:  68.59%[0GCalculating:  69.83%[0GCalculating:  71.02%[0GCalculating:  72.27%[0GCalculating:  73.05%[0GCalculating:  74.24%[0GCalculating:  75.37%[0GCalculating:  76.38%[0GCalculating:  77.45%[0GCalculating:  78.52%[0GCalculating:  79.47%[0GCalculating:  80.84%[0GCalculating:  82.03%[0GCalculating:  83.16%[0GCalculating:  84.17%[0GCalculating:  85.42%[0GCalculating:  86.73%[0GCalculating:  87.62%[0GCalculating:  88.69%[0GCalculating:  89.64%[0GCalculating:  91.01%[0GCalculating:  92.20%[0GCalculating:  93.45%[0GCalculating:  94.70%[0GCalculating:  95.24%[0GCalculating:  96.13%[0GCalculating:  97.44%[0GCalculating:  98.45%[0GCalculating:  99.70%[0GCalculating:  99.99%[0GCalculating:  99.99%[0GCalculating:  99.99%[0GCalculating: 100.00%[0G`
I would have expect wc to see one line and the terminal to print the last "Calculating: 100.00%"...

> If you have a wording suggestion, I can consider it.

hum maybe adding something on the --quiet option.
```
-q,  --quiet               Suppress information output. Errors will still be
                             displayed. (Progress will still output if --progress is specified other than none)
```

**Comment by animetosho** [comment]
Okay thanks, I've tweaked the text a little.
