### ISSUE TITLE
failed install on Mac

### ISSUE THREAD

**Issue by Diabolino** [animetosho/ParPar#25]
matt@MacBook-Pro-Matt Downloads % npm install -g @animetosho/parpar
/Users/matt/.nvm/versions/node/v8.11.2/bin/parpar -> /Users/matt/.nvm/versions/node/v8.11.2/lib/node_modules/@animetosho/parpar/bin/parpar.js

> yencode@1.1.0 install /Users/matt/.nvm/versions/node/v8.11.2/lib/node_modules/@animetosho/parpar/node_modules/yencode
> node-gyp rebuild

  CXX(target) Release/obj.target/crcutil/crcutil-1.0/code/crc32c_sse4.o
  CXX(target) Release/obj.target/crcutil/crcutil-1.0/code/multiword_64_64_cl_i386_mmx.o
  CXX(target) Release/obj.target/crcutil/crcutil-1.0/code/multiword_64_64_gcc_amd64_asm.o
  CXX(target) Release/obj.target/crcutil/crcutil-1.0/code/multiword_64_64_gcc_i386_mmx.o
  CXX(target) Release/obj.target/crcutil/crcutil-1.0/code/multiword_64_64_intrinsic_i386_mmx.o
  CXX(target) Release/obj.target/crcutil/crcutil-1.0/code/multiword_128_64_gcc_amd64_sse2.o
  CXX(target) Release/obj.target/crcutil/crcutil-1.0/examples/interface.o
  LIBTOOL-STATIC Release/crcutil.a
  CXX(target) Release/obj.target/yencode_sse2/src/encoder_sse2.o
In file included from ../src/encoder_sse2.cc:4:
../src/encoder_sse_base.h:31:2: error: use of undeclared identifier 'aligned_alloc'
        ALIGN_ALLOC(lookups, sizeof(*lookups), 16);
        ^
../src/common.h:42:57: note: expanded from macro 'ALIGN_ALLOC'
        #define ALIGN_ALLOC(buf, len, align) *(void**)&(buf) = aligned_alloc(align, ((len) + (align)-1) & ~((align)-1))
                                                               ^
1 error generated.
make: *** [Release/obj.target/yencode_sse2/src/encoder_sse2.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/matt/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/matt/.nvm/versions/node/v8.11.2/bin/node" "/Users/matt/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/matt/.nvm/versions/node/v8.11.2/lib/node_modules/@animetosho/parpar/node_modules/yencode
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yencode@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yencode@1.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/matt/.npm/_logs/2020-05-18T06_39_06_467Z-debug.log
matt@MacBook-Pro-Matt Downloads %

**Comment by animetosho** [comment]
You may need to manually apply the fix to yencode: https://github.com/animetosho/node-yencode/issues/8

Maybe I'll push out an update to yencode so that NPM installs work on OSX.
