### ISSUE TITLE
-d pow2 and -p parameters seems not working together

### ISSUE THREAD

**Issue by kouze** [animetosho/ParPar#3]
Hello,

I'm trying to use both parameters -d pow2 and -p to limit the number of recovery slices the .par2 file should contain and I'm facing bad results.

For example this command:

parpar -s 1536000 -r 573 -d pow2 -p 34

should generate 573 slices of 1536000 bytes each distributed in par2 files with a max of 34 slices, starting from 1 slice, then 2, 4, 8, 16, 32 and then 34 for the rest of the par2 files. I should then have 21 files (1 + 2 + 4 + 8 + 16 + 32 + 34*15 = 573)

Unfortunately the program generates only 10 files (+ the single .par2), for example:
test.vol000+001.par2
test.vol001+002.par2
test.vol003+004.par2
test.vol007+008.par2
test.vol015+016.par2
test.vol031+032.par2
test.vol063+034.par2
test.vol127+034.par2
test.vol255+034.par2
test.vol511+034.par2

Where are the rest of the files?

This is working fine with other software like MultiPar.

Thanks

**Comment by animetosho** [comment]
Thanks for finding and reporting!
