### ISSUE TITLE
ParPar recurse for rar files in a folder in Windows

### ISSUE THREAD

**Issue by Sonic3R** [animetosho/ParPar#31]
Hi

I have several rar files inside a folder and I saw that under Linux might work like

`parpar -s 2M -r 10% -m 3000M -o "/156570e54cd242c1847ed39a4b923e11.par2" "/156570e54cd242c1847ed39a4b923e11*rar"`

But how about for Windows in command prompt ?

I tried:

`parpar -s 2M -r 10% -m 3000M -o "F:\8043f2ba7cce429683acd5bad\8043f2ba7cce429683acd5bad.par2" "F:\8043f2ba7cce429683acd5bad\*.rar"` but I got:

>ENOENT: no such file or directory, stat `'F:\8043f2ba7cce429683acd5bad\*.rar'` since that folder `8043f2ba7cce429683acd5bad` have over 10 rar files (all have rar extension !)

**Comment by Sonic3R** [comment]
I figured out, works like:

> parpar -s 2M -r 10% -m 3000M -o "F:\8043f2ba7cce429683acd5bad\8043f2ba7cce429683acd5bad.par2" "F:\8043f2ba7cce429683acd5bad\test.01.rar" "F:\8043f2ba7cce429683acd5bad\test.02.rar" "F:\8043f2ba7cce429683acd5bad\test.03.rar"

**Comment by animetosho** [comment]
Yeah, ParPar doesn't expand wildcards like `*`. Linux shells often do this for you, but Windows won't.

If it's all in one folder, you can just specify the folder and ParPar will know to pull everything from inside it.  
Otherwise, if you need wildcards, you can probably do something like this:

	dir /b *.rar | parpar [options] -o output.par2 -i -
