### ISSUE TITLE
Cannot reset recovery buffers whilst processing

### ISSUE THREAD

**Issue by hypercube-software** [animetosho/ParPar#32]
Windows binary v0.3.1 running on a Xeon W3690
Running ParPar on a giant archive (around 200GB with multiple RAR volumes) with slices set to 7 MBytes

```
Parity file not generated: Multiply method used: XOR JIT (128 bit), 12 threads
Generating 19.21 GiB recovery data (2810 slices) from 192.08 GiB of data
[eval]:1154
		if(this._processStarted) throw new Error('Cannot reset recovery buffers whilst processing');
		                         ^
Error: Cannot reset recovery buffers whilst processing
    at PAR2Chunked.bufferedClear ([eval]:1154:34)
    at PAR2Chunked.setChunkSize ([eval]:1858:8)
    at PAR2Chunked.setRecoverySlices ([eval]:1792:9)
    at PAR2Gen.freeMemory ([eval]:2685:18)
    at [eval]:2991:9
    at [eval]:4192:16
    at next ([eval]:8445:25)
    at [eval]:2949:19
 ```

**Comment by animetosho** [comment]
Thanks for reporting!

I suspect the issue is due to something file I/O related (where it currently barfs out before displaying the actual error). Are you able to check that there's no issue reading from the source files or writing the output (e.g. out of disk space)?

**Comment by hypercube-software** [comment]
mmh, the destination drive where the PAR2 are generated was full. I guess a better error message should be used instead.

**Comment by animetosho** [comment]
Thanks for confirming!
