### ISSUE TITLE
Unexpected size alert

### ISSUE THREAD

**Issue by mramirkhan** [animetosho/ParPar#33]
Hi,

I'm backing up some personal videos that is in folders of 25GB each (to burn to BDR).

When I've pointed parpar to the 8 disc folders I get an unexpected error.

D:\discs>d:\temp\parpar -s 6M -r 23.1G -R -o c:\temp\my_recovery.par2 disc1 disc2 disc3 disc4 disc5 disc6 disc7 disc8
Too many input slices: 31230 exceeds maximum of 32768. Please consider increasing the slice size, or reducing the amount of input data
Enter `parpar --help` for usage information

31230 is < 32768 so why the error ?

**Comment by mramirkhan** [comment]
I'm going to write out one BD-R of par files, just in-case some of the data goes bad.

**Comment by animetosho** [comment]
Thanks for raising the issue.

Yeah, that's a bug. The error is correct, but the displayed number is incorrect. There's a fix for it here: https://github.com/animetosho/ParPar/commit/0294ca02bbada534535b287dcdc6f0cd8217ca67

Basically, you'll need to increase your slice size (6M in your example) until that error goes away.
