### ISSUE TITLE
Error running parpar on MacOS

### ISSUE THREAD

**Issue by df-a** [animetosho/ParPar#34]
IHello there,

I'm on catalina btw. Every time I run parpar, I get an malloc error.

file.iso is a 2.1GB linuxmint iso.
command `parpar -s 1M -r 64 -o my_recovery.par2 file.iso`

Result:
```zsh
Multiply method used: XOR JIT (128 bit), 1 thread
Generating 64 MiB recovery data (64 slices) from 2061.98 MiB of data
ParPar(20553,0x11b65ddc0) malloc: Incorrect checksum for freed object 0x7faa02557f98: probably modified after being freed.
Corrupt value: 0x39b70000b4cb
ParPar(20553,0x11b65ddc0) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      parpar -s 1M -r 64 -o my_recovery.par2
```

command `parpar -s 10M -r 500 -o my_recovery.par2 file.iso`

Result:
```zsh
Multiply method used: XOR JIT (128 bit), 1 thread
Generating 5000 MiB recovery data (500 slices) from 2061.98 MiB of data
ParPar(20785,0x117b0adc0) malloc: Incorrect checksum for freed object 0x7fa3c8452dd8: probably modified after being freed.
Corrupt value: 0xc3e900001e67
ParPar(20785,0x117b0adc0) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      parpar -s 10M -r 500 -o my_recovery.par2
```

It keeps aborting, giving me the same `malloc: Incorrect checksum for freed object` error. Of the resulting par2 files, `my_recovery.par2` will be 0 bytes; the others claim to have "all files correct" when I open them but nothing shows up to check. Macpar shows empty when I open any of the par files, not showing the file.iso.

I'm on Catalina, parpar has been installed with npm.

**Comment by animetosho** [comment]
I installed Big Sur on a VM and gave this a try, but am unable to reproduce your issue unfortunately. I did the following from the 'clean' install (however clean an unofficial version can be):

# install build tools by entering `cc` on the command line
# install NodeJS 16.13.0 via installer from the NodeJS website
# ran `npm install @animetosho/parpar` - this built without issues
# ran the command `node bin/parpar -s 1M -r 64 -o my_recovery.par2 README.md` from within the ParPar install directory

As such, I can't really investigate this by myself unfortunately. If you want to help, feel free to post a GDB backtrace and re-open the issue.
