### ISSUE TITLE
Error using version 0.4.1 with ngPost

### ISSUE THREAD

**Issue by xJayson** [animetosho/ParPar#46]
Hi, I just updated ParPar to the newest version, 0.4.1, I haven't changed any of the configs on my ngPost config file, but I'm getting a weird error generating par2

Command executed from ngPost configs:

```
Generating par2: /home/bin/parpar -s5M -r1n*0.6 -m2048M -p1l --progress stdout -q -o /tmp/xxxx/xxxx.par2 -R /tmp/xxxx

Error during par2 generation: 4
user@server:~$
```

Just like that, posting stops due to this error. Does it have to do with the current used arguments?

**Comment by animetosho** [comment]
Thanks for the report.

I just noticed that the automated Linux amd64 builds are broken for some reason - I assume that's what you're using?  
If not, can you try running the command manually without the `-q` flag? Be careful with the '*' character when doing so, as your shell may try to expand it.

**Comment by xJayson** [comment]
> Thanks for the report.
> 
> I just noticed that the automated Linux amd64 builds are broken for some reason - I assume that's what you're using?  
> If not, can you try running the command manually without the `-q` flag? Be careful with the '*' character when doing so, as your shell may try to expand it.

Yes, you're right, I do use the amd64 build.

**Comment by animetosho** [comment]
Thanks for confirming. No need to try again with that build, as it's known to be broken.

I've updated the [release page](https://github.com/animetosho/ParPar/releases/tag/v0.4.1) with a fixed build - would you be able to try again with this build instead?

**Comment by xJayson** [comment]
Thanks for the update. But the error is still showing up..

I don't if it's only on my end? Maybe we need other testers to confirm.

**Comment by animetosho** [comment]
Can you run the command without the `-q` and post the output? Make sure that the `*` is escaped.

**Comment by xJayson** [comment]
Same error.. The output is the same as the above: `Error during par2 generation: 4`

**Comment by animetosho** [comment]
Sorry, I meant to run the command *outside* of ngPost:

	/home/bin/parpar -s5M '-r1n*0.6' -m2048M -p1l --progress stdout -q -o /tmp/xxxx/xxxx.par2 -R /tmp/xxxx

**Comment by xJayson** [comment]
Showing this:

```
[Error: ENOENT: no such file or directory, stat ''-r1n*0.6''] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: "'-r1n*0.6'"
}



Error during par2 generation: 1
```

**Comment by animetosho** [comment]
Since you're running it from ngPost, try this instead:

	/home/bin/parpar -s5M -r1n*0.6 -m2048M -p1l -o /tmp/xxxx/xxxx.par2 -R /tmp/xxxx

**Comment by xJayson** [comment]
`Error during par2 generation: 4`

**Comment by EsacrihT** [comment]
Sorry to bother, but I'm also having issues with the Linux builds.

I've tried the workflows from past days including the latest static-amd64 release, and all fail with "Illegal instruction" when running the par2 creation command under Ubuntu (WSL2).

![papar_illegal](https://github.com/animetosho/ParPar/assets/59102325/b417429a-68a3-495d-9127-b61b6e28e739)

**kernel_log:**
[parpar-v0.4.1-linux-static-amd64_kernel.log](https://github.com/animetosho/ParPar/files/11582042/parpar-v0.4.1-linux-static-amd64_kernel.log)

I must say that running ParPar via NPM works fine, but the Pre-Built Binaries won't work.
I've tried different parameters (CPU methods) but the result is the same.
Only --help and --version commands work.

**Comment by animetosho** [comment]
Urgh thanks for the info. Looks like the pre-built binaries are still problematic :(

I'll look into why it's inserting unexpected instructions.

**Comment by methanoid** [comment]
FYI the latest 0.4.1 x64 build reports v0.3.2 for me if I type "parpar --help"

**Comment by animetosho** [comment]
For whatever reason, GCC is inserting AVX instructions in the wrong places for the full NodeJS build (doesn't do it for NPM build), and I'm not sure why at this point.  
Clang doesn't seem to do this, so I've redone the build with that. Would you be able to retry the [linux-static-amd64 build here](https://github.com/animetosho/ParPar/releases/tag/v0.4.1)?

> FYI the latest 0.4.1 x64 build reports v0.3.2 for me if I type "parpar --help"

Can't reproduce unfortunately. Can you double-check that you're using the new version? If you're sure it's new, could you post a hash of the EXE?

**Comment by xJayson** [comment]
Working now, thanks!

Tried the newly made build with the original command and it worked:
`/home/bin/parpar -s5M -r1n*0.6 -m2048M -p1l --progress stdout -q`

Btw, is there a difference in speed with this clang build?

**Comment by animetosho** [comment]
Thanks for the confirmation!

> Btw, is there a difference in speed with this clang build?

I wouldn't be surprised if there's a difference, though in which direction, I don't know. I wouldn't expect it to be significant though.

**Comment by methanoid** [comment]
> For whatever reason, GCC is inserting AVX instructions in the wrong places for the full NodeJS build (doesn't do it for NPM build), ~and I'm not sure why at this point~. (edit: ah, figured it out now) Clang doesn't seem to do this, so I've redone the build with that. Would you be able to retry the [linux-static-amd64 build here](https://github.com/animetosho/ParPar/releases/tag/v0.4.1)?
> 
> > FYI the latest 0.4.1 x64 build reports v0.3.2 for me if I type "parpar --help"
> 
> Can't reproduce unfortunately. Can you double-check that you're using the new version? If you're sure it's new, could you post a hash of the EXE?

I think I must have confused matters by having used NPM to build and then using the downloadable file. When I zapped files from /usr/bin and re-did NPM I have new version. Sorry, false alarm
