### ISSUE TITLE
compatibility with newer node versions?

### ISSUE THREAD

**Issue by ICE-COOL-LEMONADE** [animetosho/ParPar#47]
is parpar compatible with node versions above 12? tried node 20 and it throws an error about libnode.so.72, then attempting to reinstall libnode72 reverts the installation back to node 12.

**Comment by animetosho** [comment]
Your error sounds like you're building it for the wrong version of Node.  
When doing your NPM install (or `node-gyp rebuild`), make sure it's compiling against Node 20 and not some other version.

**Comment by ICE-COOL-LEMONADE** [comment]
thank you, i wiped all node versions as well as parpar directories and started fresh. looks to have worked :)
