### ISSUE TITLE
Trojan:Win32/Bearfoos.A!ml anybody else get this flag today?

### ISSUE THREAD

**Issue by greatdealnzb** [animetosho/ParPar#49]
got this today from silly windows firewall

Trojan:Win32/Bearfoos.A!ml

parpar.exe

**Comment by animetosho** [comment]
Trying the latest Windows release binary, VirusTotal [reports no detections](https://www.virustotal.com/gui/file/133770531a5848c558c2bd14861b72c40a52feaf722716a204f0438ba0540ff8) (was previously submitted, but I requested a reanalysis, but it didn't change the outcome).

Are you able to check the SHA256 of your parpar.exe matches `133770531a5848c558c2bd14861b72c40a52feaf722716a204f0438ba0540ff8`? Perhaps try uploading your copy of parpar.exe to VirusTotal and post the link.

**Comment by greatdealnzb** [comment]
https://www.virustotal.com/gui/file/133770531a5848c558c2bd14861b72c40a52feaf722716a204f0438ba0540ff8

https://pasteboard.co/WLne4gTr1Igp.png

coming up safe bud, bit weird really

i have the same file in 2 locations being used and only 1 gets flagged, i guess it is windows being stupid

**Comment by animetosho** [comment]
> i have the same file in 2 locations being used and only 1 gets flagged

Are you certain that the two copies are identical, and one wasn't just altered by something malicious?
