### ISSUE TITLE
-r does not wotk with %

### ISSUE THREAD

**Issue by prdp19** [animetosho/ParPar#54]
Hi,

at help.txt i read
`-r15.7%: generates 15.7% recovery`

Does not work. I get

```
Values for out and input-slices are required
Enter parpar --help for usage information
```

`%PARPAR% -s 1M -S -r15.7% -o %dir%\filename.par2 -R %dir%\`

For example

`%PARPAR% -s 1M -S -r100 -o %dir%\filename.par2 -R %dir%\`

Works. 

What am I doing wrong?

**Comment by prdp19** [comment]
Sorry, the problem was escapeing.

With

`%PARPAR% -s 1M -S -r15.7%% -o %dir%\filename.par2 -R %dir%\`

It works.

Why do I have to specify -s? That is not necessary with MultiPar and par2cmdline-turbo either?
I have files of different sizes and never know what to set for -s? Is there a value that I can use for all sizes?

An automatic function that calculates the size based on the source files would be cool!

**Comment by animetosho** [comment]
The block size/count is a required PAR2 parameter. par2cmdline and par2j just have a default value if you choose to not specify it.

From memory, par2cmdline just uses 2000 blocks (which is equivalent to `-s2000` in ParPar). par2j selects a size such that size=count\*100. Currently there's no equivalent option to replicate par2j's behaviour in ParPar (though it does exist in ParParGUI).

The block size/count incurs a number of tradeoffs, and only really the user can determine the tradeoffs they desire. Having some automatic value [has been asked for](https://github.com/Parchive/par2cmdline/issues/171), but unfortunately there's no real "ideal" value for it.

**Comment by animetosho** [comment]
Added the ability to simulate par2j's default via `-s0.5w*10`.

I think keeping `-s` as a required parameter is sensible - it's fundamental to the generated PAR2 and only really the user can determine an appropriate value.
