### ISSUE TITLE
parpar: ../deps/uv/src/unix/core.c:254: uv__finish_close: Assertion `handle->flags & UV_HANDLE_CLOSING' failed.

### ISSUE THREAD

**Issue by mohitjoshi155** [animetosho/ParPar#55]
parpar: ../deps/uv/src/unix/core.c:254: uv__finish_close: Assertion `handle->flags & UV_HANDLE_CLOSING' failed.

this error happens sometimes

**Comment by animetosho** [comment]
Thanks for the report - could you provide the following info?

* What OS you're using
* What version of ParPar you're running
* How did you obtain/build ParPar? Pre-built binaries, or installed yourself via NPM/Git?
* If you're not using a pre-built binary, what version of NodeJS are you running?
* A sample command which produces that error? Also, it'd be helpful if you could post the full output of the run.
* When does the error occur? Immediately after running the command? Once the whole process is finished?

**Comment by mohitjoshi155** [comment]
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian

parpar version 0.4.2

i am using pre built binary amd one from releases section

node version v10.19.0

command
Generating par2: parpar -s5M -r1n*0.6 -m2048M -p1l --progress stderr -q -o /tmp/EbrLp9kYflSEw3e4U/EbrLp9kYflSEw3e4U.par2 -R /tmp/EbrLp9kYflSEw3e4U
Calculating       :  40.67%
parpar: ../deps/uv/src/unix/core.c:254: uv__finish_close: Assertion `handle->flags & UV_HANDLE_CLOSING' failed.

Error during par2 generation: 6
=> par2 exit code: 6


error occurs randomly ,like when i upload a whole season in few episode files this error will occur
other times it works perfectly having no issue

**Comment by animetosho** [comment]
Thanks for the extra info!  
Unfortunately, I can't reproduce your issue, and I'm not able to see any obvious candidate as to why it's occurring.

* Can I assume this is the static AMD64 build?
* Can you do a run without the `-q` flag so that the output is shown?
* Can you try installing this via NPM or Git instead of the pre-built binary, and see if the issue crops up?
* Only if you know how: could you run this inside GDB and print out `handle->flags` and `handle->type` when the assertion hits? This may not work with the pre-built binary, so only try this with your own build from the above step

**Comment by mohitjoshi155** [comment]
yes static build
I think this error is only happening for small files like 100 to 300 mb files that also for some random files 
I noticed that increasing the slices size helps with this error to some extent
I have not encountered this error for big files yet
seems very specific issue,not a big deal 
I am closing the issue for now if you dont mind

Thanks for replying Sir, i appreciate your efforts

**Comment by animetosho** [comment]
Thanks for more info. I've been trying a bunch of things to try to find it, but haven't been successful getting anywhere.

Would you happen to be low on free memory perhaps?

Otherwise I'm interested to hear if anyone else is getting similar issues.

**Comment by animetosho** [comment]
By pure luck, I managed to encounter this. Unfortunately I can't get it to happen again, but I have a theory, so implemented a fix.

Are you able to try a build from the dev branch? Otherwise I might sort out a release with this fix.

**Comment by animetosho** [comment]
[v0.4.3 released](https://github.com/animetosho/ParPar/releases/tag/v0.4.3), which should hopefully fix this issue. If you try it out, please let me know how well it fares.
