### ISSUE TITLE
Completely broken par2 files since commit 0143a754abce3751095e9148a494e37dc42c5837

### ISSUE THREAD

**Issue by duhagppn** [animetosho/ParPar#63]
Having an issue where the latest dev of ParPar results in unusable par2 files. tested on both Linux and Windows. 

Same data files, different parpar releases.
This was generated with a version from before a RISC-V addition
![image](https://github.com/user-attachments/assets/d0f142e5-134c-4284-8400-f0756478487d)

This was generated on the newest dev branch
![image](https://github.com/user-attachments/assets/c6e383f2-e193-450c-9560-bf1a0bd61b9e)

I don't know the exact commit which screwed it up, but a working version I have is missing the following in help-full.txt: 
RISC-V only choices:
crc: compute CRC using Zbc/Zbkc

the following files are missing from the working version, so hopefully you can narrow it down

PARPAR_\ParPar03\build\hasher_rvzbc.target.mk
PARPAR_\ParPar03\hasher\crc_rvzbc.h
PARPAR_\ParPar03\hasher\hasher_rvzbc.cpp

Edit: Broken since commit 0143a754abce3751095e9148a494e37dc42c5837
![image](https://github.com/user-attachments/assets/4d713b99-af5a-4105-b047-f0e64d23c77a)

The last commit that works is 92d9c9748f9e59aef513eb7da3c899cd0a3843c4
![image](https://github.com/user-attachments/assets/1c75e602-e2cb-45b4-b274-24aedf6df12d)

**Comment by animetosho** [comment]
Thanks for reporting!

Hopefully the latest commit fixes it.

**Comment by duhagppn** [comment]
Looks to be working again, thanks for the quick fix :)
